import test from'node:test';import assert from'node:assert/strict';import{validateEntry,filterEntries,isEntry,parseImport}from'../src/model.js';import{loadEntries,saveEntries}from'../src/storage.js';import{STORAGE_KEY}from'../src/constants.js';
const valid={id:'1',fontName:'Lora',category:'serif',spotted:'Book',sample:'Hello',mood:'cozy',dateSaved:'2026-01-01T00:00:00.000Z'};
test('validation rejects blank and invalid enum values',()=>{const result=validateEntry({fontName:' ',category:'comic',spotted:'',sample:'',mood:'loud'});assert.equal(result.ok,false);assert.deepEqual(Object.keys(result.errors),['fontName','spotted','sample','category','mood'])});
test('filter combines category and mood',()=>{const other={...valid,id:'2',category:'display',mood:'bold'};assert.deepEqual(filterEntries([valid,other],'serif','cozy'),[valid]);assert.equal(filterEntries([valid,other],'','').length,2)});
test('entry schema validates stored objects',()=>{assert.equal(isEntry(valid),true);assert.equal(isEntry({...valid,mood:'nope'}),false)});
test('storage reports corrupt and blocked reads',()=>{assert.match(loadEntries({getItem:()=>'{'}).error,/damaged/);assert.match(loadEntries({getItem(){throw Error()}}).error,/could not read/)});
test('storage round trips and reports write failures',()=>{let raw;const memory={getItem:()=>raw??null,setItem:(_,v)=>raw=v};assert.equal(saveEntries([valid],memory),null);assert.deepEqual(loadEntries(memory).entries,[valid]);assert.match(saveEntries([],{setItem(){throw Error()}}),/Could not save/);assert.ok(raw.includes(STORAGE_KEY)||raw.includes('Lora'))});
test('import rejects malformed and partial backups atomically',()=>{assert.equal(parseImport('{').ok,false);assert.match(parseImport('{}').error,/list/);assert.match(parseImport(JSON.stringify([{fontName:'Missing fields'}])).error,/invalid/);assert.deepEqual(parseImport(JSON.stringify([valid])).entries,[valid])});
test('import rejects unsafe IDs, oversized values, and duplicate IDs',()=>{assert.equal(parseImport(JSON.stringify([{...valid,id:'\"><img onerror=alert(1)>'}])).ok,false);assert.equal(parseImport(JSON.stringify([{...valid,sample:'x'.repeat(181)}])).ok,false);assert.match(parseImport(JSON.stringify([valid,{...valid}])).error,/duplicate/)});
