import{CATEGORIES,MOODS}from'./constants.js';import{validateEntry,filterEntries,parseImport}from'./model.js';import{loadEntries,saveEntries}from'./storage.js';import{loadFont}from'./font-loader.js';
const $=s=>document.querySelector(s),form=$('#font-form'),grid=$('#font-grid'),empty=$('#empty-state'),notice=$('#notice'),dialog=$('#delete-dialog'),draftDialog=$('#draft-dialog'),composer=$('#composer');
const loaded=loadEntries(),mobile=matchMedia('(max-width:760px)');let entries=loaded.entries,pendingDelete=null,editingId=null,deleteTrigger=null,toastTimer,previewTimer,previewRequest=0,undoState=null,formDirty=false;
const el=(tag,className='',text='')=>{const node=document.createElement(tag);if(className)node.className=className;if(text)node.textContent=text;return node},safeFont=name=>`"${name.replace(/["\\]/g,'')}"`;
const options=(items,all='')=>`${all?`<option value="">${all}</option>`:''}${items.map(x=>`<option value="${x}">${x}</option>`).join('')}`;
$('#category').innerHTML=options(CATEGORIES);$('#mood').innerHTML=options(MOODS);$('#category-filter').innerHTML=options(CATEGORIES,'All categories');$('#mood-filter').innerHTML=options(MOODS,'All moods');
function toast(message,undo=false){clearTimeout(toastTimer);$('#toast-copy').textContent=message;$('#undo-delete').hidden=!undo;$('#toast').classList.add('show');toastTimer=setTimeout(()=>{$('#toast').classList.remove('show');undoState=null},undo?6500:4200)}
function showPersistent(message){notice.textContent=message;notice.hidden=false;notice.focus()}
function persist(message){const error=saveEntries(entries);if(error){showPersistent(error);toast(error);return false}notice.hidden=true;if(message)toast(message);return true}
function card(entry,index){const article=el('article','specimen'),head=el('div','card-head'),title=el('h3','',entry.fontName),actions=el('div','card-actions'),edit=el('button','edit','Edit'),remove=el('button','delete','×'),sample=el('p','sample',entry.sample),meta=el('div','meta'),details=el('div'),badges=el('div','badges'),spotted=el('p','spotted'),date=el('time','date',new Intl.DateTimeFormat(undefined,{dateStyle:'medium'}).format(new Date(entry.dateSaved))),state=el('span','font-state','Loading font…');article.dataset.id=entry.id;article.style.setProperty('--i',Math.min(index,8));article.style.setProperty('--card-accent',['#d94d69','#d58a45','#588b73','#7b6c9f'][index%4]);title.style.fontFamily=`${safeFont(entry.fontName)},serif`;sample.style.fontFamily=`${safeFont(entry.fontName)},serif`;edit.type=remove.type='button';edit.dataset.edit=remove.dataset.delete=entry.id;edit.setAttribute('aria-label',`Edit ${entry.fontName}`);remove.setAttribute('aria-label',`Delete ${entry.fontName}`);actions.append(edit,remove);head.append(title,actions);badges.append(el('span','badge',entry.category),el('span','badge',entry.mood));spotted.append('Spotted on ',el('strong','',entry.spotted));date.dateTime=entry.dateSaved;details.append(badges,spotted,date);meta.append(details,state);article.append(head,sample,meta);return article}
async function hydrateFonts(list){grid.setAttribute('aria-busy','true');await Promise.all(list.map(async entry=>{const ok=await loadFont(entry.fontName),node=grid.querySelector(`[data-id="${CSS.escape(entry.id)}"] .font-state`);if(node)node.textContent=ok?'Google Font loaded':'Fallback preview'}));grid.setAttribute('aria-busy','false')}
function render(){const visible=filterEntries(entries,$('#category-filter').value,$('#mood-filter').value);grid.replaceChildren(...visible.map(card));$('#result-count').textContent=String(visible.length);empty.hidden=visible.length>0;empty.querySelector('h3').textContent=entries.length?'No fonts match these filters.':'No type crushes here yet.';empty.querySelector('p').textContent=entries.length?'Try another category or mood.':'Save the next typeface that makes you stop and look.';empty.querySelector('.primary').hidden=entries.length>0;hydrateFonts(visible)}
function reportErrors(errors){for(const name of ['fontName','spotted','sample']){const input=form.elements[name],error=$(`#${name.replace(/[A-Z]/g,m=>'-'+m.toLowerCase())}-error`);input.setAttribute('aria-invalid',String(!!errors[name]));error.textContent=errors[name]||''}const first=Object.keys(errors)[0];if(first)form.elements[first]?.focus()}
function resetForm(){editingId=null;formDirty=false;form.reset();form.elements.sample.value='The quick brown fox jumps over the lazy dog.';$('#submit-label').textContent='Pin to board';$('#composer-title').textContent='Pin a typeface';reportErrors({});$('#form-status').textContent=''}
function syncComposer(){const open=composer.classList.contains('open');composer.inert=mobile.matches&&!open;for(const node of document.querySelectorAll('[aria-controls="composer"]'))node.setAttribute('aria-expanded',String(open))}
function openComposer(entry=null){if(entry){editingId=entry.id;for(const key of ['fontName','category','spotted','sample','mood'])form.elements[key].value=entry[key];$('#submit-label').textContent='Save changes';$('#composer-title').textContent='Edit typeface';$('#live-preview').textContent=entry.sample;$('#live-preview').style.fontFamily=`${safeFont(entry.fontName)},serif`;formDirty=false}else resetForm();composer.classList.add('open');syncComposer();if(mobile.matches)document.body.style.overflow='hidden';setTimeout(()=>$('#font-name').focus(),0)}
function closeComposer(force=false){if(!force&&formDirty){draftDialog.showModal();return false}composer.classList.remove('open');document.body.style.overflow='';resetForm();syncComposer();return true}
form.addEventListener('submit',event=>{event.preventDefault();const result=validateEntry(Object.fromEntries(new FormData(form)));reportErrors(result.errors);if(!result.ok)return;const old=entries,existing=entries.find(x=>x.id===editingId),entry={...result.value,id:existing?.id||crypto.randomUUID(),dateSaved:existing?.dateSaved||new Date().toISOString()};entries=existing?entries.map(x=>x.id===editingId?entry:x):[entry,...entries];if(!persist(existing?`${entry.fontName} updated.`:`${entry.fontName} pinned to your board.`)){entries=old;$('#form-status').textContent='Changes could not be saved. Check your browser storage settings.';render();return}render();closeComposer(true)});
form.addEventListener('input',()=>{formDirty=true;const name=form.elements.fontName.value.trim(),sample=form.elements.sample.value.trim()||'Aa',request=++previewRequest;$('#live-preview').textContent=sample;$('#live-preview').style.fontFamily=name?`${safeFont(name)},serif`:'';$('#preview-status').textContent=name?'Waiting to preview…':'Preview';clearTimeout(previewTimer);if(name)previewTimer=setTimeout(async()=>{const ok=await loadFont(name);if(request===previewRequest)$('#preview-status').textContent=ok?'Live Google Font':'Fallback preview'},300)});
grid.addEventListener('click',event=>{const edit=event.target.closest('[data-edit]');if(edit){const entry=entries.find(x=>x.id===edit.dataset.edit);if(entry)openComposer(entry);else showPersistent('That font could not be found. Refresh the board and try again.');return}const button=event.target.closest('[data-delete]');if(!button)return;const entry=entries.find(x=>x.id===button.dataset.delete);if(!entry){showPersistent('That font could not be found. Refresh the board and try again.');return}deleteTrigger=button;pendingDelete=entry.id;$('#delete-copy').textContent=`“${entry.fontName}” will be removed from this board. You can undo immediately afterward.`;dialog.showModal()});
dialog.addEventListener('close',()=>{const confirmed=dialog.returnValue==='confirm';if(confirmed&&pendingDelete){const before=entries,index=entries.findIndex(x=>x.id===pendingDelete),entry=entries[index];entries=entries.filter(x=>x.id!==pendingDelete);if(!persist())entries=before;else{undoState={entry,index};toast(`${entry?.fontName||'Font'} deleted.`,true)}render()}pendingDelete=null;if(!confirmed&&deleteTrigger?.isConnected)deleteTrigger.focus();else $('#board').focus();deleteTrigger=null});
draftDialog.addEventListener('close',()=>{if(draftDialog.returnValue==='discard')closeComposer(true);else setTimeout(()=>$('#font-name').focus(),0)});
$('#undo-delete').addEventListener('click',()=>{if(!undoState)return;const before=entries;entries.splice(undoState.index,0,undoState.entry);if(!persist(`${undoState.entry.fontName} restored.`))entries=before;undoState=null;render()});
$('#export-data').addEventListener('click',()=>{const blob=new Blob([JSON.stringify(entries,null,2)],{type:'application/json'}),link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=`font-crush-${new Date().toISOString().slice(0,10)}.json`;link.click();setTimeout(()=>URL.revokeObjectURL(link.href),0);toast(`${entries.length} font${entries.length===1?'':'s'} exported.`)});
$('#import-data').addEventListener('click',()=>$('#import-file').click());$('#import-file').addEventListener('change',async event=>{const file=event.target.files[0];event.target.value='';if(!file)return;if(file.size>1_000_000){showPersistent('That backup is larger than 1MB. Choose a Font Crush JSON backup.');return}const result=parseImport(await file.text());if(!result.ok){showPersistent(`${result.error} Nothing was imported.`);return}const before=entries,ids=new Set(entries.map(x=>x.id));entries=[...result.entries.filter(x=>!ids.has(x.id)),...entries];if(!persist(`${entries.length-before.length} new font${entries.length-before.length===1?'':'s'} imported.`))entries=before;render()});
function readUrl(){const query=new URLSearchParams(location.search),category=query.get('category')||'',mood=query.get('mood')||'';$('#category-filter').value=CATEGORIES.includes(category)?category:'';$('#mood-filter').value=MOODS.includes(mood)?mood:''}
function writeUrl(){const query=new URLSearchParams(location.search),category=$('#category-filter').value,mood=$('#mood-filter').value;category?query.set('category',category):query.delete('category');mood?query.set('mood',mood):query.delete('mood');history.replaceState(null,'',`${location.pathname}${query.size?'?'+query:''}${location.hash}`)}
for(const id of ['category-filter','mood-filter'])$(`#${id}`).addEventListener('change',()=>{writeUrl();render()});$('#clear-filters').addEventListener('click',()=>{$('#category-filter').value='';$('#mood-filter').value='';writeUrl();render()});for(const node of document.querySelectorAll('.mobile-add,.empty-add'))node.addEventListener('click',()=>openComposer());$('.close-composer').addEventListener('click',()=>closeComposer());document.addEventListener('keydown',e=>{if(e.key==='Escape'&&composer.classList.contains('open')&&!draftDialog.open){e.preventDefault();closeComposer()}});addEventListener('beforeunload',e=>{if(formDirty){e.preventDefault();e.returnValue=''}});addEventListener('popstate',()=>{readUrl();render()});mobile.addEventListener('change',syncComposer);readUrl();syncComposer();if(loaded.error)showPersistent(loaded.error);render();
